version: "3.8"

networks:
  docker_net:
    external: true

services:
  zk1:
    image: zookeeper
    restart: unless-stopped
    hostname: zk1
    container_name: zk1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      # 四字命令(The Four Letter Words)白名单
      ZOO_4LW_COMMANDS_WHITELIST: "stat,conf,mntr,envi,cons,srvr,ruok"
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - ./.data/zk1/data:/data
      - ./.data/zk1/datalog:/datalog
    networks:
      - docker_net

  zk2:
    image: zookeeper
    restart: unless-stopped
    hostname: zk2
    container_name: zk2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_4LW_COMMANDS_WHITELIST: "stat,conf,mntr,envi,cons,srvr,ruok"
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zk3:2888:3888;2181
    volumes:
      - ./.data/zk2/data:/data
      - ./.data/zk2/datalog:/datalog
    networks:
      - docker_net

  zk3:
    image: zookeeper
    restart: unless-stopped
    hostname: zk3
    container_name: zk3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_4LW_COMMANDS_WHITELIST: "stat,conf,mntr,envi,cons,srvr,ruok"
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - ./.data/zk3/data:/data
      - ./.data/zk3/datalog:/datalog
    networks:
      - docker_net
