# 文件名： docker-compose-kafka-cluster.yml
#docker-compose -f docker-compose-kafka-cluster.yml down
# docker-compose -f docker-compose-kafka-cluster.yml up -d

version: "3.7"

networks:
  docker_net:
    external: true

services:
  kfk1:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: kfk1
    ports:
      - "19092:9092"
    external_links:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.3 # 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 19092 # 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.3:19092 # 绑定发布订阅的端口。修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
    volumes:
      - "./.data/kfk1/docker.sock:/var/run/docker.sock"
      - "./.data/kfk1/data/:/kafka"
    networks:
      - docker_net

  kfk2:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: kfk2
    ports:
      - "19093:9092"
    external_links:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.3 # 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 19093 # 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.3:19093 # 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
    volumes:
      - "./.data/kfk2/docker.sock:/var/run/docker.sock"
      - "./.data/kfk2/data/:/kafka"
    networks:
      - docker_net

  kfk3:
    image: wurstmeister/kafka
    restart: unless-stopped
    container_name: kfk3
    ports:
      - "19094:9092"
    external_links:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 192.168.2.3 # 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 19094 # 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.3:19094 # 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
    volumes:
      - "./.data/kfk3/docker.sock:/var/run/docker.sock"
      - "./.data/kfk3/data/:/kafka"
    networks:
      - docker_net

  # 可视化工具1
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    restart: unless-stopped
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links: # 连接本compose文件创建的container
      - kfk1
      - kfk2
      - kfk3
    external_links: # 连接本compose文件以外的container
      - zk1
      - zk2
      - zk3
    environment:
      ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181 ## 修改:宿主机IP
      TZ: CST-8
    networks:
      - docker_net

  # 可视化工具2
  # akhq:
  #   image: tchiotludo/akhq:latest
  #   container_name: kafka-akhq
  #   hostname: kafka-akhq
  #   ports:
  #     - "8987:8080"
  #   environment:
  #     - AKHQ_BOOTSTRAP_SERVERS=kafka:9092
  #     - AKHQ_JVM_OPTS=-Xmx256M
  #   networks:
  #     - docker_net
